### ISSUE TITLE
Project setup

### ISSUE THREAD

**Issue by SafaeMT** [SafaeMT/blog-engine#17]
- [x] Add Readme and License #27 
- [x] Create folder structure #28 
- [x] Configure build tools #18 
- [x] Add stack libraries #29 
- [x] Add testing libraries #30 
- [x] Init the project #31 
- [x] Configure CI #32 
- [x] Configure Docker #34
